on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrhavaba.azurecr.io
        username: ${{ secrets.acr_acrhavaba_username }}
        password: ${{ secrets.acr_acrhavaba_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/app" -f  "app/Dockerfile" -t acrhavaba.azurecr.io/azooaks:${{ github.sha }} --label dockerfile-path=app/Dockerfile
        docker push acrhavaba.azurecr.io/azooaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_azooaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep azooaks8dc2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace azooaks8dc2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: azooaks8dc2
        container-registry-url: acrhavaba.azurecr.io
        container-registry-username: ${{ secrets.acr_acrhavaba_username }}
        container-registry-password: ${{ secrets.acr_acrhavaba_password }}
        secret-name: azooaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: azooaks8dc2
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          acrhavaba.azurecr.io/azooaks:${{ github.sha }}
        imagepullsecrets: |
          azooaksdockerauth
